/**
 * @module services/markdown.service
 * @description Renders final markdown from templates with placeholder substitution.
 */

import { join } from 'path';
import { readMarkdown } from '../utils/file.js';
import { PATHS } from '../app/constants.js';
import logger from '../utils/logger.js';

/**
 * Loads a template file from the templates directory.
 * @param {string} templateFilename - e.g., 'progress.template.md'
 * @returns {string} Template content or empty string if not found.
 */
export function loadTemplate(templateFilename) {
  const filepath = join(PATHS.TEMPLATES, templateFilename);
  const content = readMarkdown(filepath, '');
  if (!content) {
    logger.warn(`Template not found or empty: ${templateFilename}`);
  }
  return content;
}

/**
 * Replaces {{placeholders}} in a template string with provided values.
 * Supports nested keys via dot notation: {{section.title}}
 *
 * @param {string} template - Template string with {{key}} placeholders
 * @param {Record<string, string>} data - Key-value pairs for substitution
 * @returns {string} Rendered markdown
 */
export function renderTemplate(template, data) {
  if (!template) return '';

  return template.replace(/\{\{(\w+(?:\.\w+)*)\}\}/g, (match, key) => {
    const value = getNestedValue(data, key);
    if (value === undefined) {
      logger.debug(`Template placeholder not resolved: ${match}`);
      return match; // Leave unresolved placeholders as-is
    }
    return String(value);
  });
}

/**
 * Loads a template and renders it with the given data.
 * @param {string} templateFilename
 * @param {Record<string, string>} data
 * @returns {string}
 */
export function renderFromFile(templateFilename, data) {
  const template = loadTemplate(templateFilename);
  return renderTemplate(template, data);
}

/**
 * Composes a full markdown document from sections.
 * Each section is joined with double newlines.
 * @param {string[]} sections
 * @returns {string}
 */
export function composeDocument(...sections) {
  return sections.filter(Boolean).join('\n\n') + '\n';
}

/**
 * Creates a standard document header with title and metadata.
 * @param {string} title
 * @param {object} [meta]
 * @param {string} [meta.description]
 * @param {string} [meta.lastUpdated]
 * @param {string} [meta.version]
 * @returns {string}
 */
export function documentHeader(title, meta = {}) {
  const lines = [`# ${title}`, ''];

  if (meta.description) {
    lines.push(`> ${meta.description}`, '');
  }

  const metaParts = [];
  if (meta.lastUpdated) metaParts.push(`**Last Updated:** ${meta.lastUpdated}`);
  if (meta.version) metaParts.push(`**Version:** ${meta.version}`);

  if (metaParts.length > 0) {
    lines.push(metaParts.join(' | '), '');
  }

  lines.push('---', '');
  return lines.join('\n');
}

/**
 * Creates a standard document footer.
 * @param {string} [projectName='DevPulse AI']
 * @returns {string}
 */
export function documentFooter(projectName = 'DevPulse AI') {
  return [
    '',
    '---',
    '',
    `*Generated by ${projectName} — Automated Documentation Engine*`,
    '',
  ].join('\n');
}

// ── Internal helper ─────────────────────────────────────────────────────────

/**
 * Gets a nested value from an object using dot notation.
 * @param {object} obj
 * @param {string} path
 * @returns {*}
 */
function getNestedValue(obj, path) {
  return path.split('.').reduce((current, key) => {
    return current !== null && current !== undefined ? current[key] : undefined;
  }, obj);
}
